// Generated by https://quicktype.io

export interface ActorFilmResponse {
  cast: FilmByActor[];
  crew: FilmByActor[];
  id: number;
}

export interface FilmByActor {
  character?: string;
  credit_id: string;
  release_date: string;
  vote_count: number;
  video: boolean;
  adult: boolean;
  vote_average: number;
  title: string;
  genre_ids: number[];
  original_language: OriginalLanguage;
  original_title: string;
  popularity: number;
  id: number;
  backdrop_path: null | string;
  overview: string;
  poster_path: null | string;
  department?: Department;
  job?: Job;
}

export enum Department {
  Production = "Production",
}

export enum Job {
  ExecutiveProducer = "Executive Producer",
  Producer = "Producer",
}

export enum OriginalLanguage {
  En = "en",
}
